name: "Docker Stack Deploy"
description: "Deploy a Docker Stack"
author: "Shane"
branding:
  icon: "layers"
  color: "green"

inputs:
  host:
    description: "Docker Host"
    required: true
  port:
    description: "Docker Port"
    default: "22"
    required: false
  user:
    description: "Docker User"
    required: true
  pass:
    description: "Docker Pass"
    required: false
  ssh_key:
    description: "SSH Key File"
    required: false
  file:
    description: "Docker Compose File"
    default: "docker-compose.yaml"
    required: false
  name:
    description: "Docker Stack Name"
    required: true
  env_file:
    description: "Environment File"
    required: false
  args:
    description: "Extra args to pass to docker stack deploy"
    required: false
  # registry:
  #   description: "Docker registry to log in to"
  #   required: false
  # registry_username:
  #   description: "Username for the Docker registry"
  #   required: false
  # registry_password:
  #   description: "Password for the Docker registry"
  #   required: false

runs:
  using: "docker"
  image: "Dockerfile"
